### PR TITLE
FIX: single dimension problem

### PR DESCRIPTION
**Pull request by kmuehlbauer**
1. fix single dimension problem (nrays=ndims)
2. assign root after reading sweeps (moved from @egouden)

done in #395 
3. VolumeTimeSeries class + test (VolTS, with @egouden) 

Test data for 1.& 3. possibly provided by BOM Australia, waiting for feedback

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@egouden You might have a look into this. I had to copy your `assign_root` part due to the other changes a simple merging wasn't actually feasable. Tomorrow is a day off here, hope to get your things in on friday.

**Comment by egouden** [comment]
OMG
I have been playing with this as well... see my updated PR.
Does your VolTS works from the DWD files?

**Comment by egouden** [comment]
Yes we can discuss this on Tuesday ;-)
Now I am taking some holidays...

**Comment by kmuehlbauer** [comment]
> Does your VolTS works from the DWD files?

Yes, it works well with the DWD data. I've checked with an updated version of the DWD notebook. Now the real adventure can start.

**Comment by egouden** [comment]
It does not work with sweep by sweep inputs.

**Comment by kmuehlbauer** [comment]
> What if my scanning strategy is like this:

| Volume | swp 1 | swp 2 | swp 3 |
| --- | --- | --- | --- |
| 0 | 3 | 1.6 | 1 |
| 1 | 4 | 1.6 | 1 |
| 2 | 2 | 1.6 | 1 |
| 3 | 3 | 1.6 | 1 |
| 4 | 4 | 1.6 | 1 |
| 5 | 2 | 1.6 | 1 |
| .. | .. | .. | .. | 

Right, this doesn't work. The requirement on the input files:

- OdimH5: files have different elevation angles (for PPI) and belong to same volume (eg. DWD data)
- OdimTS: files contain same structure of sweeps.

We just can't combine different elevation angles (with possibly different number of bins and gate length) into one consistent xarray dataset.

**Comment by kmuehlbauer** [comment]
taken over by #395

**Pull request merged**
