### PR TITLE
WIP: update docstrings, refactoring

### PR DESCRIPTION
**Pull request by kmuehlbauer**
- py2.7 works, there are some issues with the docs which I will have a look into locally.
- py3.4 breaks, due to some conda-forge problems (it's actually dropped in conda-forge)
- py3.5 works

Suggestions to proceed with this PR:
- [x] drop py3.4. 
- [x] fix building docs
- [x] update release notes
- [ ] review docs
- [ ] add unittests for new functions

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@heistermann First set of docstring update and refactoring. More to come...

**Comment by kmuehlbauer** [comment]
@heistermann

Travis is running with `numpy 1.12 `. Some changes are in there, which break some of our numpy related code. I'll track them down and incorporate the necessary changes accordingly.

**Comment by kmuehlbauer** [comment]
@heistermann 

- py2.7 works, there are some issues with the docs which I will have a look into locally.
- py3.4 breaks, due to some conda-forge problems (it's actually dropped in conda-forge)
- py3.5 works

Suggestions to proceed with this PR:
 - drop py3.4. 
 - fix the docs

**Comment by kmuehlbauer** [comment]
@heistermann This has matured enough to be merged into the wradlib feature branch `gpm_to_wrl`.

After merging we can work together finishing this for the final merge into `master`.

**Comment by heistermann** [comment]
I took the opportunity to do **nothing** with regard to refactoring the matching stuff. Thank you so much for taking the lead here! 

Merge at your discretion, after that I will try to have a look at it asap.

**Pull request merged**
