### PR TITLE
improvement ipol

### PR DESCRIPTION
**Pull request by egouden**

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@egouden Just curious, could you elaborate a bit on your extension to scipy's `binned_statistic_dd`? If this is some standard use case, we should try to implement this in `scipy` directly.

**Comment by egouden** [comment]
@kmuehlbauer 
The idea is to reuse the bins for saving time.
It is certainly a standard use case.
Do you think contributing to scipy is easy?

**Comment by kmuehlbauer** [comment]
> The idea is to reuse the bins for saving time.

Makes sense, so you call it once `values=None` and get the `binnumbers` back for use in a forthcoming call?

> It is certainly a standard use case.

Then it should be implemented within scipy.

> Do you think contributing to scipy is easy?

Not sure, but you could open an issue explaining your use and outlining your solution at the scipy github issue tracker.

**Comment by kmuehlbauer** [comment]
@egouden While you are on it, do you see an easy solution for #373?

**Comment by egouden** [comment]
@kmuehlbauer 
You just need to pass maxdist to the interpolator call in comp.py
I would not allow maxdist to be initialised in ipol.py

**Comment by egouden** [comment]
> > The idea is to reuse the bins for saving time.
> 
> Makes sense, so you call it once `values=None` and get the `binnumbers` back for use in a forthcoming call?
> 
> > It is certainly a standard use case.
> 
> Then it should be implemented within scipy.
> 
> > Do you think contributing to scipy is easy?
> 
> Not sure, but you could open an issue explaining your use and outlining your solution at the scipy github issue tracker.

I just send a message to the scipy-dev list.

**Pull request closed without merging**
