### PR TITLE
Add RADVOR product types RV and RQ to radolan.

### PR DESCRIPTION
**Pull request by heistermann**
Please see issue #591 .

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@heistermann Great to have you back ;-) We need to be careful. With respect to the precision. Are those two really hourly data?

**Comment by heistermann** [comment]
No, RV is 5 minute data.

**Comment by kmuehlbauer** [comment]
Can you link official documents with description? If this is some new format, we might need some adaptions.

**Comment by heistermann** [comment]
And the same for RQ:

`{'producttype': 'RQ',
 'datetime': datetime.datetime(2022, 10, 14, 11, 0),
 'radarid': '10000',
 'datasize': 1620000,
 'formatversion': 5,
 'maxrange': '100 km',
 'radolanversion': '2.29.1',
 'precision': 0.1,
 'intervalseconds': 3600,
 'nrow': 900,
 'ncol': 900,
 'radarlocations': ['asb',
  'boo',
  'drs',
  'eis',
  'ess',
  'fbg',
  'fld',
  'hnr',
  'isn',
  'mem',
  'neu',
  'nhb',
  'oft',
  'pro',
  'ros',
  'tur',
  'umd'],
 'predictiontime': 0,
 'moduleflag': 8,
 'quantification': 1,
 'nodataflag': -9999,
 'secondary': array([], dtype=int64),
 'nodatamask': array([     0,      1,      2, ..., 809997, 809998, 809999]),
 'cluttermask': array([], dtype=int64)}`

**Comment by heistermann** [comment]
Ah, and RV and RQ are also contained in the more verbose [RADOLAN/RADVOR composite format doc](https://www.dwd.de/DE/leistungen/radolan/radolan_info/radolan_radvor_op_komposit_format_pdf.pdf;jsessionid=AEACAAF9B8529EEF4C844D264194761F.live31084?__blob=publicationFile&v=16).

**Comment by kmuehlbauer** [comment]
OK, thanks, I think the RQ can stay in that list, the RV would need to be moved to accompany "WN" above. But I'm not really sure, we need to test that the DataArray has the correct gain/offset.

**Comment by heistermann** [comment]
Why put `RV` together with `WN`? It is not in units of dBZ, but mm of precipitation in a 5 minutes interval, as far as I understand it...similar to `RY`, but analysis plus 24 forecasts from +5 to +120 mins.

**Comment by kmuehlbauer** [comment]
Then we would need to have another "elif" catching RR with 2byte data. RY is only one-byte.

Thegain/offset stuff is needed, because the data is not read until requested from the DataArray. Otherwise we would loose lazy loading.

**Comment by heistermann** [comment]
Isn't RY also two-byte? (`attrs["datasize"]==1620000`)

**Comment by kmuehlbauer** [comment]
Yes, mixed that up with RX :roll_eyes:.

**Comment by kmuehlbauer** [comment]
So, that means everything should be OK as is here in that PR, right? What a fuzz...

**Comment by heistermann** [comment]
Too many product in the RADOLANverse.

**Comment by heistermann** [comment]
But I am confused after looking at the code again. `RY` is considered to be a rainfall rate in mm/h, but it is a depth in mm/5min (see [here](https://www.dwd.de/DE/leistungen/radolan/produktuebersicht/radolan_produktuebersicht_pdf.pdf?__blob=publicationFile&v=9)).

**Comment by heistermann** [comment]
Same holds, in my view, for `RZ`, `EY`, `EZ` and `YW`.

**Comment by kmuehlbauer** [comment]
according to the linked doc RY unit is (1/100mm)/5 min which is a rainrate, right? As in CF-Metadata the Rainrate is in mm/h the output is like this. I'm not sure, the DWD docs are quite irritating with respect to that...

**Comment by heistermann** [comment]
When I read, e.g., `RY` via `read_radolan_composite`, the values are 12 times lower as compared to rading the same dataset via `xr.open_dataset` - which makes sense if we consider the unit RY to be `mm/5min` which should be converted to `mm/h` on the fly. However, that might cause obvious issues if one considers the unit of RY to be `mm` (rainfall_amount/RA )rather than `mm/5min` (rainfall_rate / RR).

**Comment by kmuehlbauer** [comment]
Rainsum/Rainamount would be just mm. This was my thought at least.

**Comment by heistermann** [comment]
Yes, I see.

**Comment by heistermann** [comment]
Maybe this is just a problem on my side...since I, so far, interpreted this as a depth, not as a rate. I was just wondering if users might be confused if they get different number when using read_radolan_composite and xr.open_dataset.

**Comment by heistermann** [comment]
But taking the RADOLAN product docs verbatim, you are right that it is a rainfall_rate.

**Comment by kmuehlbauer** [comment]
Yeah, it turns out that you have to know what you do. Using the DataArray there is clearly described what the unit is, so the confusion should be minimal there. But I have no idea, how to better handle that. I would rely on your expertise here.

**Comment by heistermann** [comment]
You are right! But how do I find the unit of the DataArray if I use `xr.open_dataset`? I cannot find it under "attributes".

**Comment by heistermann** [comment]
Or, to be more specific:
`ry = xr.open_dataset("rydata", engine="radolan")`
`ry.attrs`

gets me

`{'radarid': '10000',
 'formatversion': 3,
 'radolanversion': '2.29.1',
 'radarlocations': ['asb',
  'boo',
  'ros',
  'hnr',
  'umd',
  'pro',
  'ess',
  'fld',
  'drs',
  'neu',
  'nhb',
  'oft',
  'eis',
  'tur',
  'isn',
  'fbg',
  'mem']}`

So is it possible that the main portion of metadata is lost on the way? Or maybe I should read the docs first...

**Comment by kmuehlbauer** [comment]
Yes, not needed metadata or due to the fixing unreasonable metadata is removed. 

But the units are here in the DataArray not the Dataset: `ry.RY.attrs`.

**Comment by kmuehlbauer** [comment]
commits squashed and added to #594

**Pull request closed without merging**
