### PR TITLE
WIP: georeferencing fixup

### PR DESCRIPTION
**Pull request by kmuehlbauer**
Further georeferencing fixup:

New functions:
- `georef.polar.spherical_to_xyz`
- `georef.polar.spherical_to_proj`
- `georef.polar.spherical_to_polyvert`
- `georef.polar.spherical_to_centroids`
- `georef.rect.xyz_to_spherical`
- `georef.misc.bin_altitude`
- `georef.misc.bin_distance`
- `georef.misc.site_distance`

Fixed functions:
- `georef.satellite.correct_parallax`
- `georef.satellite.dist_from_orbit`
- `vis`-functions

Deprecated functions:
- `georef.polar._lonscale`
- `georef.polar._latscale`
- `georef.polar.polar2lonlat`
- `georef.polar.__pol2lonlat`
- `georef.polar.polar2lonlatalt`
- `georef.polar.polar2lonlatalt_n`
- `georef.polar.polar2polyvert`
- `georef.polar.polar2centroids`
- `georef.polar.projected_bincoords_from_radarspecs`
- `georef.misc.hor2aeq`
- `georef.misc.aqe2hor`
- `georef.misc.beam_height_n`
- `georef.misc.arc_distance_n`
- `georef.satellite.sat2pol`
- `io.gdal.open_shape`
- `vis.plot_cg_ppi`
- `vis.plot_cg_rhi`
- `util.deprecated`

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@heistermann 

We should take the opportunity to deprecate a lot of functions, which are not used any more:

- `georef.misc.hor2aeq`
- `georef.misc.aeq2hor`
- `georef.polar._latscale`
- `georef.polar._lonscale`
- `georef.polar.polar2lonlat`
- `georef.polar.__pol2lonlat`
- `georef.polar.polar2lonlatalt`
- `georef.polar.polar2lonlatalt_n` which should be replaced in the documentation with the new workflow
- tbc

**Comment by heistermann** [comment]
:+1:

**Comment by kmuehlbauer** [comment]
@heistermann For handling of deprecation I want to suggest [this](http://deprecation.readthedocs.io/en/latest/) package. So we do not have to track all that deprecation stuff and can remove that util.deprecated. Thoughts?

**Comment by heistermann** [comment]
- Reg. the `deprecation` package: absolutely!
- Reg. functions to deprecate: absolutely! In particular, `polar2lonlat` and `polar2lonlatalt` are still used behind the scences in e.g. `polar2polyvert`, `polar2centroids` which has been annoying for a long time.

**Comment by kmuehlbauer** [comment]
> Reg. functions to deprecate: absolutely! In particular, polar2lonlat and polar2lonlatalt are still used behind the scences in e.g. polar2polyvert, polar2centroids which has been annoying for a long time.

Just my thinking, let's clean up that stuff.

**Comment by kmuehlbauer** [comment]
Regarding `polar2polyvert`, `polar2centroids` should we take the opportunity to make a clean cut?

- `polar2polyvert` -> `spherical_to_polyvert` 
returning xyz and aeqd-projection if parameter proj=None, otherwise use proj and reproject

- `polar2centroids` -> `spherical_to_centroids` same as above

**Comment by heistermann** [comment]
👍

**Comment by kmuehlbauer** [comment]
@heistermann @IreneCrisologo

I pushed new updates for the gpm/trmm matching. Please consider this ready for review. I would be very much interested in your opinions. 

I had to retrieve new orbit files, so you need to update your local copy of `wradlib-data`.

**Comment by IreneCrisologo** [comment]
Hi Kai, where can I find the updated io_func.py?

**Comment by kmuehlbauer** [comment]
@IreneCrisologo Sorry, seams I missed to add the io_func.py. Will do tomorrow.

**Comment by kmuehlbauer** [comment]
Hmm, but io_func.py has the latest changes. You would need to fetch the branch from my fork.

**Comment by IreneCrisologo** [comment]
sorry for the stupid question.. how do i do that?

**Comment by kmuehlbauer** [comment]
You would need to add my fork  as a remote to your local wradlib git repo. Then you can fetch that branch from my fork. I usually do those stuff with my IDE, so I have no command line snippets at hand. @heistermann probably knows this by heart.

**Comment by heistermann** [comment]
I think
```
$ git remote add kai https://github.com/kmuehlbauer/wradlib.git
$ git fetch kai
$ git checkout -b kai/georeferencing-fixup
```
I'll help you tomorrow if there are any problems.

**Comment by IreneCrisologo** [comment]
image

i'm getting an error...

**Comment by kmuehlbauer** [comment]
@IreneCrisologo Let's discuss this on the gitter channel https://gitter.im/wradlib/wradlib

**Comment by kmuehlbauer** [comment]
@heistermann I updated the first comment with all changes (new functions, fixes, deprecations). This is now (hopefully) ready to go from my end. Major changes are in `wradlib_match_workflow.ipynb` with an updated matching processing.

**Comment by kmuehlbauer** [comment]
@heistermann Green lights, ready for review.

**Comment by heistermann** [comment]
`wradlib_match_workflow.ipynb` runs smoothly on my machine. Results of "old method using loop" that compares refgr1 vs refsr1 looks very similar to the old results in our currrent docs. Minor differences might be due to changes in masking out -9999 and changes in georeferencing.

I am still trying to understand the "new" approach using Zonalstats as the differences to the "old" approach appear to be quite substantial.

**Comment by heistermann** [comment]
As far as I can see until here, you really did an outstanding job. I am deeply impressed - that is really worth a v1.0.

**Comment by kmuehlbauer** [comment]
@heistermann The (major) difference is, that in the former variant we average over `dBZ` not `Z`.  I do not use any fancy zonalstats weighted averaging atm. But we can think about this. 

The creation of the zonalstats object takes quite a while (30-40 s on my machine). But you can reuse it for processing and stuff, even for visualization (eg. qgis). We also could use `GridPointsToPoly` if we do not need weighted averaging in the future. 

There is also no inverse distance weighting (as suggested in the paper) and also no weighting to bin volume.

**Comment by kmuehlbauer** [comment]
@heistermann When travis is happy I'll going to merge this. Then I will cut a 0.11.3 release tomorrow.

**Pull request merged**
