### PR TITLE
improvement projection

### PR DESCRIPTION
**Pull request by egouden**
This adds a few projection tools including geoid calculations.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@egouden This is rebased to latest master, please checkout your local branch correctly. I've had problems to get one test to run. Also did not review, yet. There might be room for further improvement.

**Comment by kmuehlbauer** [comment]
Seems that your PR depend on each other `raster->ipol->projection->polar`. I tried to rebase everything but this might not be the best approach. So I'll wait for your turn.

**Comment by egouden** [comment]
This PR is independent.
Note that GDAL >= 2.2 is required for vertical datum shift.
It still fails on windows.
Maybe because of this file missing 
Since I have no access to Windows machines, could you investigate this issue?

**Comment by kmuehlbauer** [comment]
@egouden I've reassigned `strict_channel_priority` for appveyor. Let's see if things work now better.

**Comment by kmuehlbauer** [comment]
@egouden Hmm, although we got a newer gdal it still breaks. Can you just mark it as `skip` on windows?

**Comment by egouden** [comment]
Well shouldn't this work also on windows?

**Comment by kmuehlbauer** [comment]
@egouden Yes it should, but for some reason it doesn't. Until we figure out why it doesn't work, we can skip the test.

**Comment by kmuehlbauer** [comment]
@egouden Thanks! Nice addition, but we need to reiterate a bit before release of wradlib 1.7.

**Pull request merged**
