### PR TITLE
Structure notebooks

### PR DESCRIPTION
**Pull request by kmuehlbauer**
As agreed on in #70, here is the first attempt.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
Notebook tests needs fixing

**Comment by kmuehlbauer** [comment]
@heistermann How do we want to handle the converted .py-scripts. Now they are created within the same folder as the original .ipynb. I suggest to leave them there and package them together with the .ipynb files for PyPI. We could remove the examples folder altogether then.

**Comment by heistermann** [comment]
Agreed!

**Comment by heistermann** [comment]
Merge at your discretion.

**Comment by kmuehlbauer** [comment]
There are some flaws left, wrt to hyperlinks from notebooks to other docs (API etc.). I need to merge these changes here, if the CI is happy, to see which links need to be changed.

**Comment by kmuehlbauer** [comment]
Something really weird happened. Somehow to example/data files were not deleted. But I couldn't remove them any more. Reverting seemed to make everything more cluttered. I did a hard reset to the commit before the breaking changes and will redo everything from clean slate.

**Pull request merged**
