### PR TITLE
improvement ipol

### PR DESCRIPTION
**Pull request by egouden**
This is a suggestion to improve the interpolation module including:

 -   optimisation of the interpolation functions using grids
 -   new interpolation functions taking into account the fact that values represent areas instead of points
 -   _possibility to reuse interpolator in order to reduce cost_

Again the ipol module has a much larger scope than the radar applications !

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@egouden I've rebased to latest master and fixed the linter error. Please take care to reset your local branch accordingly.

**Comment by egouden** [comment]
Please see the new version.
I have two PR pending to scipy.
I rolled back using the current scipy while keeping the same functionality.
Optimisation of the code will have to wait for the new version of scipy.

**Comment by kmuehlbauer** [comment]
@egouden Thanks! I will have a closer look into it soon. Could you reference the scipy PR's here, please?

**Comment by egouden** [comment]
Again a failure related to get_srtm.
I don't know what to do.

**Comment by kmuehlbauer** [comment]
@egouden seems like somehow the download failed, but no error message is issued. Not sure, if this is some problem of the code or just some flaky connection.

**Comment by egouden** [comment]
Can I restart the CI without new commit?

**Comment by kmuehlbauer** [comment]
@egouden Yes, normally you should be able to do so in the travis website.  If you go there via details, you should be able to restart the build via clicking the button in the upper right part.

**Comment by kmuehlbauer** [comment]
@egouden I've resolved the merge conflicts locally. Please update your local branch before going ahead with this.

**Comment by kmuehlbauer** [comment]
Thanks @egouden! Great work!

**Pull request merged**
