### PR TITLE
Added default parameters for WX data format

### PR DESCRIPTION
**Pull request by franklinvv**
The DWD also supplies WX files with dimensions of 1100x900. When compared to the RX grid, the WX grid is displaced 80km towards the east, and expanded 100km northwards and southwards.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@franklinvv This is looking good to me. I added WX to the radolan showcase notebook in https://github.com/franklinvv/wradlib/pull/1. We can proceed after you merged this into your master.

Next time please consider using a branch instead of 'master' for contributing.

**Comment by franklinvv** [comment]
@kmuehlbauer My apologies, I'm not completely comfortable with the standard workflow between forks. I just merged your pull request. Do I need to do anything else now?

**Comment by kmuehlbauer** [comment]
@franklinvv ATM there is nothing left for you to do. Good work!

Regarding *standard* workflow: here is some [information](https://git-scm.com/book/en/v2/GitHub-Contributing-to-a-Project).

For a change this small (and for a project which doesn't get tons of PR's every week :grin:) it seems unreasonable to create a special topic branch in the contributors fork. But this way your changes are isolated in this branch and you can commit/revert/merge to your liking. Using the `master` for this can get complicated, if the project master (upstream) changes frequently. 

@franklinvv Thanks again for this addition. Hopefully we will see more contributions from you in the future :+1: 

@heistermann This ready for merge, I think.

**Comment by kmuehlbauer** [comment]
@franklinvv Have a look at the docs: http://wradlib.org/wradlib-docs/latest/notebooks/radolan/radolan_showcase.html#RADOLAN-WX-Product

**Pull request merged**
