### PR TITLE
MNT: fix imports, license header, requirements

### LINKED ISSUE #348: "from module import function" not recommended
It is generally recommended not to use "from module import function" to avoid circular imports.
This decreases readability too.

### LINKED ISSUE #375: nbformat and nbconvert are needed for testrunnery.py but not in the requirements

### PR DESCRIPTION
**Pull request by kmuehlbauer**
fixes #348
fixes #375

The imports in wradlib modules follow now the [PEP8 recommendation](https://pep8.org/#imports):
eg.

```python
import os
import sys

import numpy as np
import xarray as xr

from wradlib import io, ipol
from wradlib.georef import projection
```

Absolute imports are used throughout the package.

We would have some name clash with system and wradlib `io` module. This is circumvented using ìmport io as sio`. Other possible name clashes with eg. `gdal` are possible but can also be mitigated.

The function `maximum_intensity_projection` was moved from `util` to `georef.polar` because it uses polar data and the circular dependency is avoided. There is only one circular dependency left in `io.hdf` (import zonalstats.get_clip_mask). This can also be removed after some refactoring in a later PR.

### CODE REVIEW

**Comment by egouden** [comment]
Why is the diff showing some files completely changed?

**Comment by kmuehlbauer** [comment]
@egouden probably line ending or whitespace issues.

**Comment by kmuehlbauer** [comment]
@egouden It's whitespace changes. You can disable this while reviewing. There is a small *setup wheel* in the upper left area of the review page, where you can disable this.

**Comment by kmuehlbauer** [comment]
@egouden If you agree with this, I'll merge next day to go ahead with your pending PR's.

**Comment by kmuehlbauer** [comment]
Update: added handling of moved/deprecated functions

**Comment by kmuehlbauer** [comment]
@egouden This is now fixed. I'll merge right away, if you approve.

**Comment by egouden** [comment]
Nice job the imports are now consistent.
I am OK with the changes to move on but I still have a few remarks.

I would only mention PEP8 as a starting point.
This is old (2001) and as the general documentation do not actually provides recommendations to solve our issues.

Circular dependencies could not always be avoided but should not be an issue with the proposed change. This is the whole point of #348.  Do you really get an error?

I would prefer using only georef to access all georefencing functions because the subpackages structure is a bit subjective in my opinion and add unnecessary complexity to the code. 

I would also not use the "from" at all as discussed earlier.

**Comment by kmuehlbauer** [comment]
@egouden For `georef` and `io` modules, all functions from subpackages are imported into the respective module via module __init__.py.

So for the user all functions are available via `wradlib.georef.function` or `wradlib.io.function`. 

Subpackage structure might be subjective but is necessary to keep the code readable. It went a long way to the current layout but there might still be room for consolidation and improvement.

**Pull request merged**
