### PR TITLE
WIP: Notebook revision

### PR DESCRIPTION
**Pull request by heistermann**
This Pull Request prepares a revision of the noteboosk, including minor edits and improvements, new examples, and setting slideshow properties. I also added a notebook that provides an approx. 1 hour tour through wradlib - this will also be the guiding notebook in the ERAD course. 

This PR is still WIP, and it will also fail as long as the new example data have not been merged.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@heistermann Some pl/plt error in the fuzzy notebook. Should we use `import matplotlib.pyplot as plt` throughout all notebooks?

**Comment by kmuehlbauer** [comment]
This example section is getting better and better. Expect more in the next month's.

**Comment by heistermann** [comment]
After having installed

`$ conda install -c damianavila82 rise`

you can try the livereveal properties of the revised notebooks.

**Comment by heistermann** [comment]
As far as I am concerned, we can merge this. I have not revised all notebooks, but only those which will be used at ERAD2016. We can revise the rest later.

The main changes of this PR are now:
- set slideshow properties in many notebooks
- minor revisions in many notebooks
- substantial changes in the wradlib_beamblock.ipynb
- added a new function to compute cumulative beam blockage
- added a new notebook on fuzzy echo classification
- added a one hour tour of wradlib notebook
- added georef.get_shape_coordinates to library reference
- added a more concise/brief version of the zonal stats example notebook
- enhanced the numpy and matplotlib intros.

**Comment by kmuehlbauer** [comment]
@heistermann This is really great work. Thank you for incorporating these tedious changes.

**Pull request merged**
