### PR TITLE
ENH: make wradlib aware of its version

### PR DESCRIPTION
**Pull request by kmuehlbauer**
make wradlib aware of its version ,adapt setup.py, wradlib/__init__.py and doc/source/conf.py from pyart, add version and date to doc

This can go with issue  #8 , its somehow related to python2/3. Adapted setup.py with versioning applied.

### CODE REVIEW

**Comment by wradlib** [comment]
#8

**Comment by kmuehlbauer** [comment]
This needs to mbe merged to test deployment and versioning.

**Comment by heistermann** [comment]
This PR involved to modify `__init__.py`, adding

`from .version import git_revision as __git_revision__`

When I try to import wradlib, this line throws an exception:

`ImportError: No module named version`

I don't have any idea about this module...is this some Python2/3 issue?

**Comment by jjhelmus** [comment]
You need to trigger wradlib's build step which creates the `version.py` file.  Either use `python setup.py install` and changing directory so you do not pick up the source directory, or use `python setup.py build_ext --inplace` to do an in-place build.

**Comment by kmuehlbauer** [comment]
@jjhelmus Thanks, I just started to write...

**Comment by heistermann** [comment]
Thanks!

**Pull request merged**
